// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvrUyO3sv9Xuib5AHv8BEPOcuvUKa9xFlfAuLDJvacWLiXPtG0lM9JE0hicwP9+S495ecbgzWNvPmy+",
	"xGjUrVar+9cPaX/zfB7FnCFT0jv7zYuJIBEqFOavQZhIhWIUTIha6YEApS9orChn3pl3PrhqhrjGEHw7",
	"EQRKnggfgQbIFF1QFHBAA1hQDINDr+FRTRdrbg2PkQi9M89PF/EansBfEiow8M6USLDhSX+FEbGCKYVC",
	"U//vJ9L8tdN8f3/gfjTvf+s0Trsv6fjhv7/1Gp7axJq7VIKypffy8pJyMzvrD64mgq9pgOKCur2XN9cf",
	"XDVljD5dUB9iNxdWZnLDiwWPUSiKhpIskamHkMwxtH8HAdVsSDgpzduSqbG15KVhAIpDRJS/AsNWwsGC",
	"C5gTgREqEh7me+Pzn9BXms+cSHwIeES0frd38oFIBPsRNCu1wuzADrC1bDXgzsMnEsUhtnwe3XmHVf3p",
	"o1sI8oBsXV1hTCIEvjCcR3rakK31NhKJu6XPOcchUQsuIst4QZJQeWfez8kc11Qob1tNMyKWqCCl2t6T",
	"1/CQJZF39qnIIpPAu6+RQGCIWoU0Ikus7u86tqcJfI1C0ACzNR0hWMKq1dWclXOqGourulFEGFliAPMN",
	"9AdX7YtNjGK6ogtVNcGYPiALYk6ZqrL+IZmjYKhQQn8ygnQi3N5cwgFZExqSeYjwuEIGN8P++X8OjTOS",
	"4JqFm9QZK1rzOZM8xIdE0DqdITOigpsGtzejP7KYQKLwQdGo5oBmNEKpSBRbrkULfyQSLK0GGG0wRFtX",
	"QBQ2DbM91qbBa+BXA3otmKJYo2gukaHQa8Pt7egc6AIYV+CHFJlK4QUDWFNihP43Df4FvyQoNpAhMXBm",
	"N0A5a8GtxAAoMyencVQCYYGh1X9ZoG1pF7D+7J153aNj7J2cftfEf76fN7tHwXGT9E5Om72j09Nur/td",
	"r9PpaHOqA9im+/WujK1vKkw7ns/Zgi7r4ei010Tm8wADyKcap0qPjfg+StmCCY+T0CjQnGz6WSqiEglU",
	"WgtqwTCK1QaCREsAk+H4fDT+2IDJzfWPo+noemz+4gK+748uh+eGHGVrn63EtaHvJj1zq3WDBlQWISjT",
	"vxuT7T0P4k2JtNloib4VuPDOvG/aeQhvuxDXdiAz1VM1iVFXdRuDRAhkKlWng/AqkDqFeg2vqFGv4Rnt",
	"ew3P6tVreOfDy+HMfjM/zeDtuP9jf3TZ/3A51PD7+g4b3lNTr9tcE6FTBKkFSPdj5MylKQ+XRSt9S+Us",
	"DWZCl0YLO6iOV6eX9pap+iFCKWtjyUUSEdbUKjAo6OYBmfNEWe2XzmQfg0ji4HdDY0ikAsvg9+LjSzFv",
	"+2TN83478OlTJRg3U7As5HTmgDMv+c39etE84jARJCw4kdfwJGXLJCQiH83jLvGjphtsShRr6mMzzd1a",
	"gR+1KG+nRC95LL6ksiZoTsiSMgM9IZVKO0dBinL0zT5UmFxWSanCSO7pwF6eQRAhyEb/zfBJPcRkiQ+K",
	"/4w1Cd9MD+v8a4E6jdRHrmlA02hZBMokNGns/unKFSoSEEWqq6VfavKwspL+cH78A26aaxImCJZVzYoV",
	"8W2R8YYTpg6hJ7sQS6Th/MM/JVxwqTBweoDIbbdlJ18lUsEcIWH0lwThkaoVtV6mbJpqICwmPrZ2BdnP",
	"qWLKrmY2d7/70MY8wBqb1MNgY24iTF7x5tn5nCnBw4c4JAzftF07eaLnphHokYufnYO8RvrfZpolesUa",
	"py4Elvc1dR6vqfLajbI4UZD+mW+X7NxsVLD1PXw0cw1tbqnG96Czp/NiVjcI9bBKS9HXqMt1q444dtsP",
	"Vlk7lAL6aylDTS33LkWvOy9PZKaTViH8p4qqK53WKKRZ6ZWaI6KMC3Azd9eg3dZx5847bMEViWOT5mpn",
	"IWG40WBGGOQ1RcorTZy1noiicxpStdHls6BPcHA9mECv9QT/Mn7cbR08/aN7fHhoUmYdiMI1BoY1pJ0O",
	"XcZNUemcW7PtD67gIpm33vTE0hnkSmnktlTrptuOUk3Q7AwwfgfausqWXOOoSV0BOE6iuS4lFuBXOMr8",
	"pLuN48ZJLqk+gKUNQn6cvMZ1MLkFnwuUEKOoWUNrgjIa6VWO6vhHGHGxqYsuenwH14LpnH78cOfpX8dH",
	"+tdhuQQ6/fhhC327zff3n0xpc3D14fnjh+fZh8Nv65oTUnFRm8hN7Ye3RTvqpLKddDo1wunvv0+6OoQc",
	"CsFrmgs33w/gfe/kO+MpISVMAeqZ2g9iziTCwUTweYgRnKMi1EXXi9lsAv3JSB627tgdO8cFZRhA7Kbq",
	"1eWZ/gLwDDMNMbrKf4YZVSHCs6W3iTI8m1nN7L/nrf+7vyyvVqvVdqvINmVrEtKgScQyiXRu/AwjOwSF",
	"oV6nA3XUjKvmgicsgGcYcwXp716nVzufhDox2DTxiUol4Rn6dgCygV7nfS1lwmLBdd2qs4qmhlq1gWe4",
	"LQ5DNtw7OoL63VrYM7t0P207AczhwjOc7NhqwvL+yjOk0F8ePekc19LGKCIqNWw1A2QUtYom2RhkY70d",
	"9AkjiVrp3fkmadb73h7pdbqa9o6NucIzqC6pkXmbEREIgTM8l1tpuLpj80SZdsoGFWBElbKdMsI2sCIs",
	"CHWUM4aobTkM+aOhXencj/6KQVOGyfKO+Zyt9WIuMi24eCQiaJYjis7rTBDRgEwoQ6FD5F0VfwPjPG9m",
	"nPikocImI1mmorgNvty3NaCP9X1YqQjzaxBJu57ABRrSPJZn/K3Dl7hn9V4iaDOjrcfB+haC8XDXP/At",
	"0mdMKVPHRxr6yZOF/pP37wuBoNvp1IUCpY+sBm9XXKiGPb5ckTKJIiI2aevCWWPdBurTo7LOXH60oWxp",
	"7cxozAX1NBtaKRXLs3Y78CNdXGrgbS2pWiVzXV7uBC2vsS9lBlj7k5Qxa3+6igfuT7rlpvsTpvj2WUul",
	"APY5RFUw1lnYniZf24Yy+KvD3Gj8Y/9ydN6/+Xh7NRzPvEb+aXw9+/76dnxeHOtfmgbU8H9G09m0+GEy",
	"vLkaTaej6/H5cDwalohux/3b2cVwPBsN+rPyp9F4NrwZ9y+3pmeNqNLw5OZ6MJxO9QfNbPYf7347fXUW",
	"bj2vLlO9QBLW9UHteOr/krJliIqzrCdewcf6duqAMM6oT0LbT3XOXGCSp0srK8k+fdJdiFWUuYb3Zh/m",
	"9WiStYW3qq3SKvs0qbJd7rTWPbqC9Q3BKfqcBeawfISpAW9hHTiT8fhUQ/OOJQpQvbP4m05gntAwyAq1",
	"zKsKiW+r0+p8dnvRmWp2eu4yOa+43L4/uwPpVF7sOtqhtOloLDu7mc67kNlZfUYT0tHozVXuoeu7Y3bZ",
	"rQ6lI82bHeWuzo7baj96q8dQuR6vLTUKzZqKAdhvf0rF+pizksU6svuH69QC5zcZ71GgFtj9bSrTepm+",
	"ZEn6Yt8O8LSNSHxz2u71x/ngCiY2iGvfFcbtXIB3Qd3nUTHWV/vCaZ2TvdLoT0Ym/TXX5zqXK1xGuz68",
	"6RzdYAAXREE/WOuMOkjbQHBl7t1NXXnQH1zZjlF++25q4ZnOrfVKVEJMhEqj1jnVupgnyvDjSVDidq65",
	"uZ0Yrk7o7O4QQrpAf+OH6e2/prtjPomJqUUoSqDMD5NAbyy9GG5AgCHaX5qrC8gRZ1RxfTJG5G++Aa3v",
	"G1xqGS1GpN3LO9aEd+/GJMKzd++ghGGx/ebUrJMKPSXtGtpvSRxzHUUm7lWG1FPS9xeN/AHI1vQfLWyb",
	"2ecbRiLqw8GcSAyAs+2unIS8juUsbc4dWpbXMdodGV6Dm2F/NmyAvbRrmFtiU62F1EcmsWCB/Zj4K4Qj",
	"E4vKBvj4+Ngi5nOLi2Xb0cr25WgwHE+HTU2TFyyeFii1oNQmJwWbLISpNPq9NDweIyMx9c6841an1XMh",
	"zUBjm8S0ve6SMF6Rbrt4ybREVZd9qEQwCQTiytUVCcPc9gvPSmyFuOVALc+IZfU5Ctw11qBw+1V4Jvap",
	"/vrJ1NKo/FVaS+24gjIvwsyTh/xJWOFyq/gGrAI1FSy2dSawDO/dOrq0FkY7BhRj+1inbumIPNm7NUl/",
	"xdLq2cukk85rJa4pal8LJS/mBtw23cxZHnU6KTaijYQkjkMXLts/SZtf5YLscbVgLjQN8r5xG/nS8Hqv",
	"Lu/KqX98nhi2CVkjQNq20xkdSmXX73659bdaUnb94y+3fqWhpiU4+bIn4FqK0rYU0U1seK6VkppJETF0",
	"nCfL4ksMaR47xLzu4nxgnltpHGL4WI29JvSWn7O1YFa4EEqDmo6sRG6YvxKc8UT+1x0zcJU9XxMO8GgU",
	"YUCJwtB16kj6BMgFQnOpCx+HM2hXHhqMgpc7pjjEPAxLT5B0XUIZSmn7fGVAtHsc5DeIryHiwL73IlLS",
	"JcOg/plsfzhpdo+PD1swWgC37cyGQU53UulbMq3Y29vReeXymUScLc25pQtUod5e7NUhHw28P/XB7b2t",
	"21CqDzzY/NkIZ027/F74pQKs3b9m2e3T3TZbRhXN4eUrvP7/wmuv8/7LSZAaAyndGRkxjo6+5EHINMXO",
	"H0rnd/B/y6hjIdVFjcKTnmrgeWnsSI3TvspbGbK5Byq1Ll3x9nYm/BHVRd6C/IvSuIu0PVRR5MU+Um8p",
	"1tH4K/R/LijULfKaOgsx0iozRFXTcBg5wJNZFWpKjvQQbXTPPm1HdagN6nesENXL+cEjDUMd9gRGfI0B",
	"LASPrB42UmEEnPmF5cyFNyqsDePnZkc7w3jdGeVT2uV/H1OT2PdqkiO3iVwd5WjxFa17Xx6tWfos4G8J",
	"jNZISw/WarPxNyEvcC87jHPmPWOnhLyrRJXceoZci4N/mdt0vmTa5pTy1fu+el+t933EvHJNbaU+K3Fv",
	"MetrwBvO8w5321i947ErQuTtX8hcT+b12iDv4ey44TQBv5Y2zS/uX/4vAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
