// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpbc9u4kv4rKO5UHWcPqavjHOtly5dMopnIycaOps6MvC6IbEkYgwAHACUrOfrvWw2AlCjSljN7JpWH",
	"fZNIXBp9+frrBr8EsUwzKUAYHQy+BDpeQErtz7M4Bm1/0SRhhklB+QclM1CGgQ4GRuUQBgnoWLEMXweD",
	"YDwi1E4jsRQzNs8VtW/CINuZ+SXQenGX5VPO4rt7WOOT6jrX12+Je0/uYU1mUpFy6dZEDMXvEBtIyJJR",
	"EnOZJxETzLTtzynVYP+S6ZpkSi5ZAgpnTcQH/4+kNMuYmA8mIiI/51MYM2UGOyuRXIO6pIbigLNfrgdW",
	"jIwyZR98zhUMSFVIfPHm4sOAMKENFTGQFAxN/Brj0YrinHkO2pA410am7LNVzgTVAw80zTgEA1RNBEnv",
	"5cvuKTk7Ozu76F99phdd/uvlsHt18/olPhu+dsNbrVYQBmad2YlGMTEPNpvyiZyimoJNGFzINJXiRwY8",
	"0XVtu7dkZl8TJmKeJ5AQJgjlnGhQSxYDwUWJziBmMxZbyVGpNwvQUKiZLEFpJgUT85DAgwGh2ZRxZtYh",
	"oSIprREVy1TdpDWpe0qsgBq4MyyFuuA3LAVtaJqR1QIEMQsgCrTMVQxkRTVxkxNy9PHHC9Lv909fVFTd",
	"6/ROok436vZvup1BvzPodH4NwmAmVUpNMAgSaiCyO4eBApq8F3xd+P2e0sOAJXX5Pgn2Rw6EJSAMmzFQ",
	"1pN3xWztWX+ZRnQad3t9VAQ1BhSu8z+/0ehzJzq9PfI/otsvnfCkuymev/ivH54jY+GRKOkPCmbBIPiP",
	"9hYA2j7629fO5KNi+MYKs6gf8GOhbXxNpCJcOtcgK2YWzJlEr7WBlCwYKKrixXr/zO1MySSPcVo71xFQ",
	"baxQuXmW4gunulswD2JPHa2AgLd28CYMvHvfuXWfpZcbHIpTDTV5UzzlSoEwxL0ncvakyVUuMGCec1S3",
	"4F0KWtN5Qzy8zVMqIlyGTjkCkB3nw46JOUnAUMY1oVOZGytVXJG1IlhpXKaJF5IIjA3O18+RNs+SPx+6",
	"nGpD3ArPit+Xg+OXg/6fjt8NjvgjZwqSYPBb1Sl24ua2AVsvmb7/yizJlMkpJwnT91VErcMfzWjMTEOK",
	"xG1J8dqGG8kxc+l8NmMP5Gh0HpI35yG5Oa8qrdvpvDnfQxeEkL8fjc7/9eb8XzfnL34IGqwpaJMZrRQ7",
	"+HaUO8jz4T8evXA5gigpDVlKnqdA0lwbMgWCSyZkEkylNJOgNRFnpQqtbjSJqcBUbEdqwtk9kElgc2oQ",
	"kknA5Rx/gIn3gwqXPASh/1lFz6c9wh4/3NqjyRNeKyVVA0j+eEFe/aPziiCicEaFIYAj0eEzKTTUrO7C",
	"9GB8w0PGqXB4W2ZUI4lZME1k7EI7hopi0BZ/w8P8zeV7G9z+nGSaGxt8QpoiVydNvlBQnIaM93FIFMzA",
	"buyzHdNb6dzBH5Gtbd/qdrfXh+OXJ68i+MfpNOr2kn5Ej1+eRMe9k5PucffVcafT2Y3zXLGo3DR4FDcb",
	"9Hlz86FA6VgmFWmOO51yJSYMzEHhUoYZ3nDu64VUhiyq9tF5mlK1LhJApuSUQ1o58lAsKWcJGYosN02i",
	"F2npKTX7+FsjQONGTskeu7Z7LYzJ9KDdTuK05Z+2YpkWWmdOlIh5UZ6r3r1A8ds6PTVFyRukwO+vvw4y",
	"7SSCY6jBY3pOsU8fi+yukeFbXby/dsTVhgUwRViKKTGmhnI5b2KczRp/v7/1FvRsaXFFU3wZS7HE51IM",
	"yCTvdPpxwrRR0v6GyD3yLNk9mwhP5rWtRt4xkT8MiFoAj05Dkk9zYfKo12t1jkMyg0QqGvVPQxKDMFJH",
	"2iigaXSKU39hIpErPSAr9yPCLAYq6nV6vbB82O3uVkKFoph+REN7JdKFFIYyAcUoqQiWSWML7LuFznhE",
	"DKQZp8YOiqUwSDM4myoMCWYgLWurs9GQDC93KquhXbv0uX3CZHXzPEdscsC3QHkTmXXPCzzQTMw5GClK",
	"XlLzlGZOfEGFFCym3JPiKvurnETeP5/1HZC3vu6hsjAMHiIKWVRK5k6E+VKj/hZOTbdhkPFcUY4IYh/h",
	"XqV2CqnxQc6pKkftSODIVMHTW4g/TLb9MBRsBKlU669DBDenigDk6OPZ6EW928A+N0S0XwBfPk2fWhMx",
	"opkNEFe+p26mr493WwxVpnXyJ4jWPhFF0ZucuFrHPKq5pzVaW3Uf8zwZO1y3T8QZ53KlCUY8Zo7tUA0G",
	"cVNbJWPZMVVA7xEsM6kMdf2BCnYj47PFHEbOmiiI5VygmahICJsLqYDk4l7IlXDjrAA/w1oTqspmhNqB",
	"aE2OoDVvheQ+n8KSKROSZYpAFRK60mjhMeU5VOc/clri1LVv7i8BXVmFF+ToxinX9FsPnKq5rRiL7RvG",
	"5d1WOczJhoOW6cPYZQt0qFfN3Z39cv3xMr0oZCwzK9TjK3ZU7lwuQQmUqjURnzRSwvUzmkC1iON0CvxJ",
	"t6yhXFXin2EdLdEktummHZOk8zm6DQo6Y9wATm1NxLk0C3JvrS8SsnSGLGoMt0HdWCCWTEmRgkCKs+1A",
	"BGEgVwIQx0pXNkDToEnxzTVRqW18XeUJIy9VtUrC/GArnIzW2wPpOkpgGS2RN6b04R2IOWadk34YpEwU",
	"f7uP1DqR//X1tc7t445208iQrnddpHpqeg/aUWC65pImRAOfRW76tDApCCTNmiiZI160LRvd6QuCyFOU",
	"zmoiLnhIENp6cEptGRXzXBv70CwUYPEPKqJZFiWQSjzSbqetiW5fG6l8a+X5qchPOtDzthVtXW2PNwMc",
	"rH10hkFHdQzR+pA/P6GGcKBIjQW4JapF9bbhuK2/cZHLYug2Uuo+OR5ZZisNDAjWjbik20RthcICEsRM",
	"qhgSFIdmGS8ghcMSuLMeEr6DzTnbStlYxx668d3SRlQpuq65qlNqk6+OR4/rekTjBRPPJXTVJufWs/ca",
	"t8+uWw8TvgziQ6oaj65xVI0v4MPbQ9QOhf2yTO9Ysqnwu2VacDtP5SpB0kzjlqkVYjx6x7SpK+8DnTNh",
	"m3icoZvOyHika4oX8GDuMjqHOyPvQTS0C/GxdWYFRjFYFrUuziSZLUVmSLJzbqpcGNY/Zb9eDE+Gv79e",
	"j3qfOlc3/+y/++XT8ftfhmZ089P9aN1dXF1+6r27+e/11e//fLi6fN2/ujxbjS5+Om1CiKVz42f583i0",
	"kza2Dtzgq9fe5JTz97Ng8NvT61auczbh01hV1TQtb/We2sDf/W3CwDLeO3lwRlHV21uGgs0/NcFzflvf",
	"lJj7ZPPdD0MbxFl+UPc4Zj887MRSwu3WO+esY8ntPt4XTDWicyG1YTFZemBJHbBUcdzC+NDdqmkSVy7b",
	"jnY7zWHJz0JSvdV4MREZzzUZj7ak1K8ws9W1vS0JiT+Pu23b75a0qoW/UVRoW5/b8p9OtVE0NlXZt10B",
	"QQ1b2pZeSo3D9Lofe7t8fSv84sOnA+kzlrlowJerPJ2CwuBfbpfSOyXb0i2dY6Z6umA7tomHpUgzuvXe",
	"354rOXnq3rKx/dGZdDILQ2OUuk5wfUuFFLSpvJs++zAMwoCzGIS2QeFYZnCW0XgBpNfCHJIrvtPRW61W",
	"LWpft6Sat/1c3X43vHh9df066rU6rYVJ+U4D86AAy7LsWHYpzxa0i7NlBoJmLBgE/VandezK24U1UNsj",
	"4xxMUw41uRKa0DIN7IUMgrZ3WCmGSTAIMJ/4XEEVTcGA0hYZ98p4+oAmI6J0BJ8FSAbKZgZkHzjyjxxs",
	"0Ht9pvTBpRxbY4f+0wcn+ozm3ASDbqdjSbf3CfvvSQ95PG1lLg86z24SZyf77cqyz9Rv0QvdtYHVdq/T",
	"KTwNXHzsELD271qK7Wcdh9OVzeHWhfcYbm4TwiznpDQSusPxk7v7hvffv04Kd4vSIMQ5TSzxBO17Fd5K",
	"32r/TwIeMvfdCfgxYeB7/N5fLb44pzV07rlWcLsJg0w2saML+4ECoUTAaj8i/MXZeERWjHNk6Ba4MCgh",
	"IdJR9DKKfeXjIK0aSG6T8ehQJJXtnvGIDC+LFkGaSdu5td9SPO6+LDnsttZ05zJZ/xs91hlqC8yYZDa1",
	"GOn+23esffdUfGuiy1Dh628eIsV1krvDsbuffrvdL6SYcRYbEjmvNQtHLWwfhHKse9YEHph2X14c93rf",
	"TrZx2U0g8BBDViDY94YiJSLYeK2AyCa0ObZonD+Wav21QLyA+N4G8aFMX0WLN2DeFg38vyzTvC16//We",
	"8897Ctk9zo5GituJUitflukw2Th1cDBN3yrY54TW2PpMydR9DFO2j6o6cTMPI2j9ey9/+zMeIRX1gnkA",
	"tc2GEj9R+mAfyL6OCBw3NDxGftPvBJeGl0TnuA0kTobjb4gAI/tdw0zmIvkeI790z3rkh82R/gZMgzdP",
	"14QZXbTzhpdNEf5/cuW/zIE7f3GW/i5Y7P+HwuFQcI7dkAH995qFy7oquE0z1t4WqbflpAPt3+0HhykV",
	"dG672bv+HNTruUpuLX1Ib2cVl9q3m/8NAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
