// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpdc+K40v4rKr17Qd41H8nM7tnlXGwxhEmoSQgFJHtOTXIoxW5AG1nySHISNuG/n9KHjcGGJFs7U3Nx",
	"7rBstbpb3U8/avGEQxEnggPXCrefcEIkiUGDtE9XgqUx9KMh0QvzHIEKJU00FRy38XH3HFGuNOEhoP4x",
	"qkVhXM8G6jRCjNwCO8ABhkcSJwxwG5MkqUdEk/q9FY0DTI2oxCwQYE5i85F7N6URDrCELymVEOG2likE",
	"WIULiIlTVWuQZvZ/PpP6n636rzc1/6N+89QKfj5cZeMHv/2AA6yXiZGutKR8jlerVSbN2tqTUsiykaOP",
	"XfTr+5/+gYyfGCVcIzBfIgkqEVwZExIpEpCagnLzNaGsLOk0jQmvSyARuWWA4DFhhBPzEqkEQjqjIdIC",
	"6QVVSIRhKiXwEMp6G5c5H5fXuOT0SwqIRsA1nVGQaCakE+m03hA8EzImGrdxKmldwgx2rqg00amqsGky",
	"GSL3EoUi2hBKuX53tBZGuYY5SCNNU80qlB8vhNRosekmlcYxkcsqpdzAthS7j8i8yzQCnsa4/Rn3B1ed",
	"s/7xtDM6uTzvDSY4wIOLyfTjxeXgGAe4czbqdY7/Pe39qz+ejHGAh73ReX887l8Mpse9Qb9nProcdC4n",
	"p73BpN/tTOxIfzDpjQadM/fyqtM/63w46+EAf+z0z3rH0+Go170YHPcn/YsBvnm901fF2P/s3mauu8m/",
	"Frd/QKiNN06BsKosdePZJinK5wy04CZ+RSrDcvwmlcneJVxwGhKGzHskZkgvoChkneMLp4nRn0QXnC2z",
	"3H19WBV1rpD9hnAYeQ1dRKwTY0Pq3S+qrrSQZA51BfKehlBPpLinEchGFMYNKpq5VTs38EVz00TTuCrw",
	"IRQ8sptjFF0A8kqgTAnjCqkhKmr97udWa+eihWy7B6nsOuVltxa5TSmLUPZ90UGHjVaj9bKJ1TGbb6NH",
	"+fUC3iGlcA7wY51AUs/Daw33ygj2e3ET4ISlkrA8MMwqeYjnJYPyecqILIamX+8NG2+M+5TeguSgQQ39",
	"R6fUF04SRdT4lbBhIZtmhCkItvy+llLPgX941UUKtKZ8rkoZScIQlJrGBs7aT/gHCTPcxv/XXJfupi9k",
	"TVexO3bCufneZpk1cBoyoiqSbexed81bZCowqol7kJJGoNB4iCKYkZTpg6qc85X69Zo5nVYV+PVKj7ot",
	"3bQgm7p258IIQTMpYptOIdGEiXnJsXf5Tryk/a6drzTFe3ScQLjT3XnNdwzAlOlQAjEBgIgNhxo1yRcb",
	"NawRiZDalcRMgs9fs/5BybaQJCSkelkFiV9SUBqiXFL2LapBY94I0DU+bLVO6DXeJG920OVxzrwMvfqx",
	"dn3dcL8Ofqv16POQPk/o8wl9PqfPn+hz73n4PHk+eT5//lTJxAIcgyaGFr4yiLKvV9Zoux3TRRY3++Zv",
	"bV6AvQ+n1cVjXPBwkVTV4lRpdAvoOksu7yrPNPxgAdh2IOTG8gU3BOvtu9kTYDvKZ9dSPJ3VfF+rs83O",
	"KXuty0Qa9e5thCVkyQSJUKpAecLI07ho1HB0cdU3bKg/OMEBHl0O/C9HdHCAj3tnvYkbsz97xxUeCPyp",
	"oqy2G885BZKQSFDG6XlO5My3FO0md2BaXV8nNAalSZyghwVw6wwHXOiBKJd2trTmlT0iGupW1iuqOo2+",
	"1tEoJo9nwOeGjv38LsAx5dnjYfD248+LhlQTv5xAWd63g0A5lVWzbMPLHNCj5L60LQLqBm0kjF3McPvz",
	"66a7aaubba0sNYv+avwwojRy8/9qEG2jgrHzzaQo24On/Pi82mBI/j3eIET5Pr2BEPk5qzyVC3Sj5DuT",
	"tY6/IMMSGqgruJaCKUS0JuEitkAVigQQ4RFKQMZUGXpoPvAlUfBrbhyJahXU6Z9IwWYtNIyFcssd1EHj",
	"mhcwbAQk+l1SDRcOREZ+X84JX/pH+9o+3xQjfHvmDlQ7o0pXOIHMKTfxgRhV2gCyj58MEsqcj8OjniaG",
	"tmlxBxXsfWKGLW+QoCWFe4OSJjTNTGRmmnUkqJRptZu72cWohli9rvauT1qYSEmW1Qxoq07vBpWs4llD",
	"MnBxnKjkEouZe6jhU9nG7bqotIjRHSzr94SlBtKoVK5FQuZzW2Z4hGaUabASKixzLaqX8N6IWceqLV2O",
	"WXd6w/rh0dHBX0L3uv/1/3v7Wk5HlZCqBlFBqfwrg2rSnTuNops18RVn+DeeLm5FyiPX6bILvmYRD2nV",
	"zv9gBQ7NqVJp4NrzCLuYBWxyTygz1PnNSGwXvNkd4Dshz+d3vNmB+kgZqKXSEOMAf2AivKuiiLbDNxOW",
	"1giuSWgRxfdGTaQNpcj02Eqr3niCOsO+DemYcGJjOsk9k3NAn/uotu21LiM0VgfXXPBiAIcsVRqkQoKj",
	"W1gQNjPgctw9b1zziSGLblHGxINCnZ7tCfKIyMhlVyi4WyVcIhJKoZSZm4G2chjNaAhcQcHWTkLCBaAj",
	"23pIpT3ma52odrP58PDQIPZ1Q8h5089VzbN+tzcY9+pHjVZjoWNWaDcWYz87hGUEPzsXGDsKHYqs8bEK",
	"sEiAk4TiNn7XaDXe+26GDfgmSWjz/pCwZEEOmwVYnUNFLTAVAhHGtvZiXQrQA9ULA+A06w6niTn7YauE",
	"tGP9yEu6yot6sXP/eXvRc/JI4zRGPI1vQfrCYBFYmfCw5SLrxX9JwfZb/SbE5NHVIUX/tN2cvAHvGwO4",
	"/VOrou0buyVx+7DVall484/lHtUq2F3c9lS0Km0LFbOo6naKWQro+vd2p45arSzdgNtNI0nCfCFq/qFc",
	"+2wt7+U6aYmAzeWqQ47KirY5hKeWHs1SxpYm0t7v1SWR4pZB/OPbdHKXGxXq9Pk9YTRC0vUEUCGKVgH+",
	"6duqYioeYRYWQLoLC4vI2R2AT551zGsyt9Q3G7kxpxhRxcC6tqAhgjg87Mq8HWh4UEo8J+wqo857M+8i",
	"cUQFhYwC1xlthQhtcYYG+t3UKk+2owBRjc4vx5NrHhMdLmy/qJHRpYYJdz9DxFRrM8GkSpGEUIU0sXkk",
	"RXzNywLWdMSz5Jeu6baSzV7QrXf97z2uVqasDdIPIlr+zdnq4nHzrnFVwojDr7JqZRPEE7DvDRxsj8jp",
	"8eu308P7xNZF28ki8Wak1zKCfYAIMwxvieCRKtfie3909O1UXfdWN4hvJAzhFtqp9V1Cq0fIHNXK2LoK",
	"qqlOdkOyi/GMQKeSuyb2YuM2MutMOhZWwtkT0Kfru8SvVK5Ps+udktcyckgVyq4dN13mrym7CwjvCh7z",
	"Evc4rNiise5ioKtOlXYckfX/A8oV66pbrk9u3q76VOWM9SfNjf98VBCl9zsbt86MKsx6/82xwuTazJwL",
	"v8tc8xu7J9eCnalkWeO+mLhdblOLqsT6StHR+nYlch+D/l/AbQbcCei9yO5vwqop7Kdfdh+Y84N500aD",
	"F73j/xyhAUqUh6JaM8kMhIMd0MLoDMJlyMB1NeytaKWgzKbVzeq/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
