// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case FAILEDPRECONDITION:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for StorageSpecServiceType.
const (
	Storage StorageSpecServiceType = "storage"
)

// Valid indicates whether the value is a known member of the StorageSpecServiceType enum.
func (e StorageSpecServiceType) Valid() bool {
	switch e {
	case Storage:
		return true
	default:
		return false
	}
}

// Defines values for StorageStatus.
const (
	DELETED      StorageStatus = "DELETED"
	DELETING     StorageStatus = "DELETING"
	FAILED       StorageStatus = "FAILED"
	PROVISIONING StorageStatus = "PROVISIONING"
	RUNNING      StorageStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the StorageStatus enum.
func (e StorageStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case DELETING:
		return true
	case FAILED:
		return true
	case PROVISIONING:
		return true
	case RUNNING:
		return true
	default:
		return false
	}
}

// Defines values for VolumeAccessMode.
const (
	ReadOnlyMany  VolumeAccessMode = "ReadOnlyMany"
	ReadWriteMany VolumeAccessMode = "ReadWriteMany"
	ReadWriteOnce VolumeAccessMode = "ReadWriteOnce"
)

// Valid indicates whether the value is a known member of the VolumeAccessMode enum.
func (e VolumeAccessMode) Valid() bool {
	switch e {
	case ReadOnlyMany:
		return true
	case ReadWriteMany:
		return true
	case ReadWriteOnce:
		return true
	default:
		return false
	}
}

// Defines values for VolumeMode.
const (
	Block      VolumeMode = "Block"
	Filesystem VolumeMode = "Filesystem"
)

// Valid indicates whether the value is a known member of the VolumeMode enum.
func (e VolumeMode) Valid() bool {
	switch e {
	case Block:
		return true
	case Filesystem:
		return true
	default:
		return false
	}
}

// Error RFC 9457 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type Error type code
	Type ErrorType `json:"type"`
}

// ErrorType Error type code
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status string `json:"status"`

	// Type Resource type identifier
	//
	// Example: k8s-storage-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// KubernetesProviderHints Kubernetes-specific PVC settings
type KubernetesProviderHints struct {
	// AccessMode PVC access mode. Controls attachment scope and permissions at creation
	// time (Kubernetes-specific; see service type definitions).
	//
	//
	// Example: ReadWriteOnce
	AccessMode *VolumeAccessMode `json:"access_mode,omitempty"`

	// StorageClass StorageClass name (overrides SP default)
	StorageClass *string `json:"storage_class,omitempty"`

	// VolumeMode PVC volume mode
	VolumeMode *VolumeMode `json:"volume_mode,omitempty"`
}

// ProviderHints Provider-specific hints from the catalog
type ProviderHints struct {
	// Kubernetes Kubernetes-specific PVC settings
	Kubernetes           *KubernetesProviderHints `json:"kubernetes,omitempty"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// StorageSpec Storage specification for creating a PVC (implements the portable storage service type)
type StorageSpec struct {
	// Capacity Requested storage capacity (e.g., "100Gi")
	//
	// Example: 100Gi
	Capacity string `json:"capacity"`

	// Metadata Resource metadata for identification
	Metadata VolumeMetadata `json:"metadata"`

	// ProviderHints Provider-specific hints from the catalog
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier (must be "storage")
	ServiceType StorageSpecServiceType `json:"service_type"`
}

// StorageSpecServiceType Service type identifier (must be "storage")
type StorageSpecServiceType string

// StorageStatus Current status of the storage instance (CloudEvents payload uses this enum)
type StorageStatus string

// Volume Volume resource representing a PVC instance
type Volume struct {
	// CreateTime Timestamp when the volume was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM instance ID (dcm-instance-id label)
	//
	// Example: app-data-volume
	Id *string `json:"id,omitempty"`

	// Path Resource path identifier
	//
	// Example: volumes/app-data-volume
	Path *string `json:"path,omitempty"`

	// Spec Storage specification for creating a PVC (implements the portable storage service type)
	Spec   StorageSpec    `json:"spec"`
	Status *StorageStatus `json:"status,omitempty"`

	// UpdateTime Timestamp when the volume was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// VolumeAccessMode PVC access mode. Controls attachment scope and permissions at creation
// time (Kubernetes-specific; see service type definitions).
//
// Example: ReadWriteOnce
type VolumeAccessMode string

// VolumeList Paginated list of volume instances
type VolumeList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string   `json:"next_page_token,omitempty"`
	Volumes       *[]Volume `json:"volumes,omitempty"`
}

// VolumeMetadata Resource metadata for identification
type VolumeMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name DCM instance ID and Kubernetes PVC name (AEP-122)
	Name string `json:"name"`

	// Namespace Kubernetes namespace where the PVC was created
	Namespace *string `json:"namespace,omitempty"`

	// StorageClass StorageClass name bound to the PVC
	StorageClass *string `json:"storage_class,omitempty"`

	// VolumeName Bound PersistentVolume name when available
	VolumeName *string `json:"volume_name,omitempty"`
}

// VolumeMode PVC volume mode
type VolumeMode string

// VolumeIdPath defines model for VolumeIdPath.
type VolumeIdPath = string

// ListVolumesParams defines parameters for ListVolumes.
type ListVolumesParams struct {
	// MaxPageSize Maximum number of resources per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVolumeParams defines parameters for CreateVolume.
type CreateVolumeParams struct {
	// Id Optional client-specified DCM instance ID. When provided, it MUST
	// match spec.metadata.name. When omitted, the instance ID is taken from
	// spec.metadata.name (AEP-122).
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVolumeJSONRequestBody defines body for CreateVolume for application/json ContentType.
type CreateVolumeJSONRequestBody = Volume

// Getter for additional properties for ProviderHints. Returns the specified
// element and whether it was found
func (a ProviderHints) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProviderHints
func (a *ProviderHints) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a *ProviderHints) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["kubernetes"]; found {
		err = json.Unmarshal(raw, &a.Kubernetes)
		if err != nil {
			return fmt.Errorf("error reading 'kubernetes': %w", err)
		}
		delete(object, "kubernetes")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a ProviderHints) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Kubernetes != nil {
		object["kubernetes"], err = json.Marshal(a.Kubernetes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kubernetes': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
