// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvdctu4kn6VLp65sPeQkuzY2RPd7CqWxtGOI6tseXanIm8KJlsSTkiAAUDbOrafZ99jn2wLP/yRSMlS",
	"zkxqqja5CUUCjUaj++sftJ+8kCcpZ8iU9LpPXkoESVChML/OOFOEMhTDaEzUQr+KUIaCpopy5nW9G0a/",
	"Zgg0QqbojKKAGRegFghhPtXzPXwkSRqj1/WSZcDmlD0G1c9UU0o1fd9jJNHjis+faeT5nsCvGRUYeV0l",
	"MvQ9GS4wIZZfpVBoAv/9iQT/6ATvbg/cQ3D71PHfHr3k7w//7SfP99Qy1QtIJSibey8vLzm11Q3Xt1p8",
	"AoGSZyJEEJgKlHrrbA6k3DJQJhVhIXq+lwqeolAUDf1QIFH4WVG9y/UVJjRBqUiSwsMC2aoU4YFIsLO1",
	"QGZcJER5XS8iCgNDTkuJRJcsXuZSWtuq79Hom06wup1XjjIhjxfI5lpV3r7xvYSy/OeRv/9ZvbqhtFEp",
	"r/Lz0Z8rO1thv+Batht38uraEsU9Dc0xkji+nHndT0/eTwJnXtf7S7u0qrZTr/a1nTBkM+693K6voCmm",
	"GGpy24gUWnitB+tJiqhM7s5FScBObOQkS6N/Qk1jIhVYEt+qqy9Vm/9kJXNbjOJ3f8dQeb73GBBMg9we",
	"K3gg9azKET9VAeVFk0rjTJB4RRE835OUzbOYiOr7EjS+/E2WOhI4BQhSwe9phKIVhUmL8nY5UW+jkPdZ",
	"mplTiiKqBUnicQUZrBDWAGd8U0JNyJlUglAN0+ugkpDH+il9JI80yRIgccwfMAJNLeQC9fSEMv3NGKXb",
	"GmUK55pl87WBnJ0C84wIwhTuQXHtLDV5AxT1A62Ka8DufyViP4kN2D0VnCXIFNwTQcldjBDhjDJDoCY4",
	"62yedqFihjagwD2Js11p2LGv6bpbyQ7eKqJhQua4p06VmK4ngzYsOqMhaZSPwBkKZCE2eUONowrh8mzo",
	"aBWjW1P2s7H5Lny6GpwPrydXv7Vvrwbjy+vh5PLqt0/dSe/8+d/7w/PB9eR2ylZw+WtGltqKkiVJ0+79",
	"Uev4VYmVbG4V1wWVqr6RMZlTppEKYioV8FmD36ubXAU0uk8eVZjInZFbM+W4JEKQpf7N8FF9TskcPyv+",
	"BRvsb6JfG9csUAmK9zrk0NCrZ4KeqVkXKLPYIERdYpsF8xETLpb7KZKd8zviU2IJPlC1gIxRBQfYmrd8",
	"mHrH5++nnn440Q+H3mogoaOFvx58fP98/v558v7wpyYj3RXRNvNwlPNw/G08fBsGfkRFIqLIlhAncUOM",
	"auShzgZzjskdxnLzOT/VJbdm9JlUPIEvuAwMPEFKqJA2YCTzuYmCWQQzGis0FBo214y5xX7059WQbf+Q",
	"MnBP/7I18resyJQ0wdsv2R0KhgolFKN0uCOwUHkJD/pnGZPvF9IYOWw9/RGqBy6+7GeXbpK2xxmdZ6JZ",
	"E2jaAIQ8guEYSBQJlHKn6JsLmzRu8jFmACgO+Jhyqb3afkg55kLV0XIrlpkp3+gSNbvbwoUyhkzdKusS",
	"FApYltxZ10Gj1Sw4sYjndd+enr45fS0Ku6eS3tGYqmV9oQ/8AdSCSssxlU6+kRa1BuIsQSFbUxYA4wy7",
	"MHbDGFfFUJ4pw+Fq+J4KHqKUeqrmRTASd2FQUtejF1z7SQFhnEmFAphVuSmDHC/7PPyCAoLUh4ohndnx",
	"wzG4TOhQL4OP+TJXSMKFCZRmgicrDOol2269yjqXKbLrBZ0puOKZwpXVhmyu9bh9wUn0nsTajYtDG2sw",
	"LfRPnpaNqT5YBkwU4h5vqxFJZcB2k17Tj5Uz3GrpYyv1b9ZbO/0Vmydi3mCsPTHPdJQq89NFpsQy5ZSp",
	"qrnWbH89gAl5khAWNUXCOT3g9ygEjXAvwsjudwuv5d7w4lKM/QAm91Ry/2RO+8Zkj7gptBnjTnvR2aWO",
	"dIpQbqdZLvKrKXKaeQWtrZp77UoWm1RzJb+wgRVlaaZgRjGObOhgPOhaBa3usfJcZ6d92czIyKOMoHaU",
	"iJtggvLCAe80N3fYL4b53KJ383RuvJ1qygmfF9TVZHfXssvUjoOcSJAfABhqFlkN5BNFYj6HAxKGmCqM",
	"fOMdSKgzoSzl7LApeBNV5d9pY6W5lCWzz5buutY4rwD6a7UeeZBkUsEdwrREWBuD50heqs3tq5WkKgsV",
	"/fCdhlX3uF3zi7rbeowshIYlW5fTSdnmWqpjfzwY9Yejc8/3rm5GI/v0c294Meh7vncz+mV0+Z8jz/f6",
	"g4vBZNBv2KPvDYTgDTXrq5/P4N3J6b+CPqKYEqYA9UiNPylnEuFgLPhdjAn0UREaW4v8MJmMoTceysPW",
	"lE1ZX4dEGGmlMkP16rI7Zc8w0Ud1czWEZ5hQFSM827lWOPA8Zc9B8e957X/3S9NptVptR122KbsnMY0C",
	"4lwTPMPQvoLKq5NOB+pzGVfBjGcsgmcYcQX580nnpGE0iXWMuwzwkUol4Rl69gUUL0467xrmpSgSKiXl",
	"LIiQUdQrjIt3ULw76bxpmJ0xkqmFVu/Q1B2e4ab25qRzBE2SsZGIkYh71FaDAowCwDOcNoolY+Se0NgE",
	"V895+AWrb08ts5UwqM9DuVmnurBVdTzfy0Tsdb2FUqnsttvazJQgOjJsUVSzFhfzdsTD9kIlcVvMQk3U",
	"AWAF+CNDvCEGzhLCAn1chn98TGPCrJspMM+ENFQCD0NjlWFjCc9YRMNGx/ZuBziLl67U/cB14JtwgSBJ",
	"goGBKqOadmVLyq7XmrIBCRc2oAJL+g4lcLYyZUZonAlswQj1OWKSqqUPTP+YMknZPMbAkGjBhKdBjPcY",
	"gxUK4NeMxNIAzIwKqdxa+hzuSPjlgYhoyrTpE+Xi0JY54J3CJKNR9mhdDWVopx3Xg7QC1OrXS1fDsjDo",
	"rpaoLI/IwtHKARX3BZmgQVnba0xAjUXUV/2P68sRjO1XmAkyN6BR9Slai9++6xzB//7P20OIeWhDEC1K",
	"7S5QexweLW2cAmpBFIQkM1mQ5t+w7YNOQ2Dq/aWt99MuPEc7TLN2QtnUa0HvzihRcVViNxwSpt3tHQJR",
	"StC7TNn8ioA98iYmuMhzOFLTOXuuheT+LjkLcuk03V1tcF7Gep3nCnm0chqUqTfH1TT29N27ahLb6TSl",
	"sUq7hQZfv9Ap6WLVhmWWJEQsmxhujhhWlcsd7zI/Rytp5+hzX1ugUZgEqeDarbfmVC2yuxblm32Q5+86",
	"s/BAu09ZdUO7z6u5od2nrvmg3SdWkuHdl8q9jA5ddrRu33sM9JkF90SYCpw+vOHo197FsN+7Or/5OBhN",
	"PN8bXU5+vrwZ6UCpd3E16PV/G/zX8Hpy7fneeHD1cXh9Pbwc9QejoYulejeTD4PRZHjWm5g3w9FkcDXq",
	"XdiPv/aGF733FwPvdj1sdFpktbkpLqyiZU1Phyyi9zTKSFwzXJMTUQYEkixWNFgNz7zfwRuaCLQKuess",
	"/L9H1r3Ac00x3IE0qcQHJHFTe4J9n8Os5UpxVtQEaofe3OVwRhhnNNTJHlGLPNGoECkrWAvLyS5NDZsc",
	"Q5XnBtp7gHZR6l/L81ao7nbTXuxrI6i8uuEsbW5yuMaQs8gcT2hrkI6JIrXWwhAWOwu+37zVXnDDotXi",
	"Lgpp1tmUAxeL3GU0jiAfXxXRUavT6ux97eCArDhI13ZVLuAEsnezhTuLameFfZW3VRglLxq4yj6L4hD3",
	"arJws/T2qn012y5yctlak20ot9n68uemyxFXuw6KDGzlpqSeUrgMqpHW4LFGAw50ZFwtVRvrONx0a1Un",
	"OiIJ5hhQ3/M/cZtTaKT5vGPu4CY1399sAoZq/acSsRXXBtrd88gS9b2qsJrLPjVArnK1dZ8bVSR9faq9",
	"//GarD4VXPGQO/c9I1msIWtypne2nnrakXAwORv7cNMfN6qCImKOasNt1MR8rN7tWMG90p6Tj6qQrju3",
	"F5PzWXszC4Sq7Kfx+mcfYWwDwloVwAWIIU+qcWN7u9HXb6L1EjVA1jaUEEbMRXTZoQGUVU3CmblsTdlE",
	"Bxy98RBmPI75g4TewKQ/LCIiL05zJqlUyMIlkFBwKaGytrShQ0xD1NFaKYJeSsIFwrFB6FUJPDw8tIj5",
	"bCogbq5sXwzPBqPrQXDc6rQWKokr2VMVxcraeq5243z/vfGwAuXaQxy1OpoMT5GRlHpd702r0zpxsG80",
	"uk1S2r4/InG6IEft1baWOaom923aTxBIvWFG2gp/altqTCkmS51CaTMy74aR1/UuqFRn1ca7at/xp029",
	"Iu5u1Ta6uEt4xUGgygQDE0W7IC+1tVzTWfw1Q5NUuqNJyKPttJH0H8YVFr3EhU2edrblvUcd7eS3d7w1",
	"t+9QFtFKOGwCCP3DXo/lfbdbeK90CFUZX8c+09JpMwhzkMedTm6pOpftPnkkTWN3K9PW8a5+V9LbqbJv",
	"2qkMEqyhYRaGKOUsi+Nl3qyEUUVJtEaebOXI5Y5/3Y8zWwNv4Og9ifKo36599P3W7pVpNjUxvkNaw8eb",
	"78dHrTytOTj9nqdQVKylrVijG+h7ed3HwgKs4IIicxNeVl7emmClqZfvzPTiAAGGD81XLqsoZMefVS8d",
	"t8FQcbsWxhSZyu/WMIJhv94134LhzFTrnH+K/CnL8wjUeX8cwxyZ5geBMBj2zWXLldUQeyd/kGpYH4yD",
	"o+Pjw+6UBXAUvH0D4YIIEmouIeZsrt9fayyx8Esg5g8oQiIRYtQROnABEZ1TpUe67dqy9vpI6TuQlb65",
	"rl4s0wUy0w8yYJGlX9K0Q9caODf/iccamJm/7CiV6vf904FGSDQQ8J5Hy98fDa3Gr/6dyksNho/+qIU3",
	"3b+77jSQFVD+gb9/Fvw96bz7fhyccTaLaagggD6mMV+ayp2xaKmTR9N5SVYuQP+UPsKBfBW1G53Ei78x",
	"uM2rB1ti3Ewwe7G2WKnWuQxbFmn1qkM5R/WhrLX9QRHYh7z0UQ+9XEZAJeRluVXZuTLe2QLDLxW5OYrb",
	"Zbb2JzRGaDGqhkS+b97rYDwvOe/gi+2kLb64SSTlkPb6nyo2BMEn2zqV7GaakPIHWuUcnHxXtHIHw/I2",
	"jj8lGjldfxWN/Fez6S3GAndLGPab0OYPtZfO945WymzxhxX+sMI9rPAc1Q4BgetAbE7ufvnbttpaUcVr",
	"G0Nx9DfckoXavUJhq7JMeXLX7W/2QzGdYbgMY7SlTJMINtKq7O3l9uX/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
