// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ContainerPortVisibility.
const (
	External ContainerPortVisibility = "external"
	Internal ContainerPortVisibility = "internal"
	None     ContainerPortVisibility = "none"
)

// Valid indicates whether the value is a known member of the ContainerPortVisibility enum.
func (e ContainerPortVisibility) Valid() bool {
	switch e {
	case External:
		return true
	case Internal:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for ContainerSpecServiceType.
const (
	ContainerSpecServiceTypeContainer ContainerSpecServiceType = "container"
)

// Valid indicates whether the value is a known member of the ContainerSpecServiceType enum.
func (e ContainerSpecServiceType) Valid() bool {
	switch e {
	case ContainerSpecServiceTypeContainer:
		return true
	default:
		return false
	}
}

// Defines values for ContainerStatus.
const (
	DELETED ContainerStatus = "DELETED"
	FAILED  ContainerStatus = "FAILED"
	PENDING ContainerStatus = "PENDING"
	RUNNING ContainerStatus = "RUNNING"
	UNKNOWN ContainerStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the ContainerStatus enum.
func (e ContainerStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case FAILED:
		return true
	case PENDING:
		return true
	case RUNNING:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "https://dcm-project.github.io/problems/already-exists"
	INTERNAL         ErrorType = "https://dcm-project.github.io/problems/internal"
	INVALIDARGUMENT  ErrorType = "https://dcm-project.github.io/problems/invalid-argument"
	NOTFOUND         ErrorType = "https://dcm-project.github.io/problems/not-found"
	PERMISSIONDENIED ErrorType = "https://dcm-project.github.io/problems/permission-denied"
	UNAUTHENTICATED  ErrorType = "https://dcm-project.github.io/problems/unauthenticated"
	UNAVAILABLE      ErrorType = "https://dcm-project.github.io/problems/unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for ServiceInfoType.
const (
	ClusterIP    ServiceInfoType = "ClusterIP"
	LoadBalancer ServiceInfoType = "LoadBalancer"
	NodePort     ServiceInfoType = "NodePort"
)

// Valid indicates whether the value is a known member of the ServiceInfoType enum.
func (e ServiceInfoType) Valid() bool {
	switch e {
	case ClusterIP:
		return true
	case LoadBalancer:
		return true
	case NodePort:
		return true
	default:
		return false
	}
}

// Container Container resource representing a container instance
type Container struct {
	// CreateTime Timestamp when the container was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the container instance
	//
	// Example: my-nginx-container
	Id *string `json:"id,omitempty"`

	// Path Resource path identifier
	//
	// Example: containers/my-nginx-container
	Path    *string      `json:"path,omitempty"`
	Service *ServiceInfo `json:"service,omitempty"`

	// Spec Container specification with input fields for creating a container
	Spec   ContainerSpec    `json:"spec"`
	Status *ContainerStatus `json:"status,omitempty"`

	// UpdateTime Timestamp when the container was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ContainerCpu CPU resource constraints
type ContainerCpu struct {
	// Max Maximum allowed CPU cores
	Max int `json:"max"`

	// Min Minimum guaranteed CPU cores
	Min                  int                    `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerEnvVar Environment variable definition
type ContainerEnvVar struct {
	// Name Environment variable name
	Name string `json:"name"`

	// Value Environment variable value
	Value                string                 `json:"value"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerImage Container image specification
type ContainerImage struct {
	// Reference Complete OCI image reference.
	// Format: [REGISTRY/]REPOSITORY[:TAG|@DIGEST]
	//
	//
	// Example: quay.io/myapp:v1.2
	Reference            string                 `json:"reference"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerList Paginated list of container instances
type ContainerList struct {
	Containers *[]Container `json:"containers,omitempty"`

	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ContainerMemory Memory resource constraints
type ContainerMemory struct {
	// Max Maximum allowed memory with unit (e.g., "2GB", "4GB")
	Max string `json:"max"`

	// Min Minimum guaranteed memory with unit (e.g., "1GB", "2GB")
	Min                  string                 `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerMetadata Resource metadata for identification
type ContainerMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier
	Name string `json:"name"`

	// Namespace Kubernetes namespace where resources were created
	Namespace *string `json:"namespace,omitempty"`
}

// ContainerNetwork Network configuration
type ContainerNetwork struct {
	// Ip Pod IP address
	Ip *string `json:"ip,omitempty"`

	// Ports Container ports to expose
	Ports                *[]ContainerPort       `json:"ports,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerPort Container port definition
type ContainerPort struct {
	// ContainerPort Port number inside container
	ContainerPort int `json:"container_port"`

	// Visibility How this port is exposed to consumers.
	// - none: Port is not exposed outside the container process
	// - internal: Exposed to the host or cluster network
	//   (e.g., Docker -p, Kubernetes ClusterIP Service)
	// - external: Reachable from outside the host/cluster
	//   (e.g., OpenShift Route, Kubernetes Ingress/LoadBalancer)
	//
	//
	// Example: internal
	Visibility           ContainerPortVisibility `json:"visibility"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// ContainerPortVisibility How this port is exposed to consumers.
//   - none: Port is not exposed outside the container process
//   - internal: Exposed to the host or cluster network
//     (e.g., Docker -p, Kubernetes ClusterIP Service)
//   - external: Reachable from outside the host/cluster
//     (e.g., OpenShift Route, Kubernetes Ingress/LoadBalancer)
//
// Example: internal
type ContainerPortVisibility string

// ContainerProcess Container process configuration
type ContainerProcess struct {
	// Args Arguments to the entrypoint
	Args *[]string `json:"args,omitempty"`

	// Command Entrypoint override
	Command *[]string `json:"command,omitempty"`

	// Env Environment variables
	Env                  *[]ContainerEnvVar     `json:"env,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerResources CPU and memory resource constraints
type ContainerResources struct {
	// Cpu CPU resource constraints
	Cpu ContainerCpu `json:"cpu"`

	// Memory Memory resource constraints
	Memory               ContainerMemory        `json:"memory"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerSpec Container specification with input fields for creating a container
type ContainerSpec struct {
	// Image Container image specification
	Image ContainerImage `json:"image"`

	// Metadata Resource metadata for identification
	Metadata ContainerMetadata `json:"metadata"`

	// Network Network configuration
	Network *ContainerNetwork `json:"network,omitempty"`

	// Process Container process configuration
	Process *ContainerProcess `json:"process,omitempty"`

	// ProviderHints Optional provider-specific hints from the catalog (accepted, not acted upon)
	ProviderHints *map[string]interface{} `json:"provider_hints,omitempty"`

	// Resources CPU and memory resource constraints
	Resources ContainerResources `json:"resources"`

	// ServiceType Service type identifier (must be "container")
	ServiceType ContainerSpecServiceType `json:"service_type"`
}

// ContainerSpecServiceType Service type identifier (must be "container")
type ContainerSpecServiceType string

// ContainerStatus Current status of the container instance
type ContainerStatus string

// Error RFC 9457 compliant error response (Problem Details for HTTP APIs).
//
// Defined problem types:
// | Type URI | Title | HTTP Status |
// |----------|-------|-------------|
// | .../problems/invalid-argument | Invalid argument | 400 |
// | .../problems/not-found | Not found | 404 |
// | .../problems/already-exists | Already exists | 409 |
// | .../problems/permission-denied | Permission denied | 403 |
// | .../problems/unauthenticated | Unauthenticated | 401 |
// | .../problems/internal | Internal Server Error | 500 |
// | .../problems/unavailable | Service unavailable | 503 |
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Errors Present only when two or more same-type validation errors occur.
	// Each entry describes one validation failure. Never empty, never
	// single-entry. Top-level detail equals the first entry for backward
	// compatibility.
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Pointer JSON Pointer fragment identifier (RFC 6901 §6) locating the request body field that caused this error, e.g. "#/spec/resources/cpu/min". Absent when the error cannot be attributed to a single request body field or is not a validation error.
	Pointer *string `json:"pointer,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the error type
type ErrorType string

// ErrorDetail Individual validation error within a multi-error response
type ErrorDetail struct {
	// Detail Human-readable explanation of this specific validation error
	Detail string `json:"detail"`

	// Pointer JSON Pointer fragment identifier (RFC 6901 §6) locating the request body field that caused this error, e.g. "#/spec/resources/cpu/min". Absent when the error cannot be attributed to a single request body field.
	Pointer *string `json:"pointer,omitempty"`
}

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status string `json:"status"`

	// Type Resource type identifier
	//
	// Example: k8s-container-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// ServiceInfo Kubernetes Service details
type ServiceInfo struct {
	// ClusterIp Cluster-internal IP address
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// ExternalIp External IP address (for LoadBalancer type)
	ExternalIp *string `json:"external_ip,omitempty"`

	// Name Name of the Kubernetes Service
	Name *string `json:"name,omitempty"`

	// Ports Service ports
	Ports *[]ServicePort `json:"ports,omitempty"`

	// Type Service type
	Type *ServiceInfoType `json:"type,omitempty"`
}

// ServiceInfoType Service type
type ServiceInfoType string

// ServicePort Service port details
type ServicePort struct {
	// Port Service port number
	Port int `json:"port"`

	// Protocol Protocol (TCP, UDP)
	Protocol *string `json:"protocol,omitempty"`

	// TargetPort Target container port
	TargetPort int `json:"target_port"`
}

// ContainerIdPath defines model for ContainerIdPath.
type ContainerIdPath = string

// ListContainersParams defines parameters for ListContainers.
type ListContainersParams struct {
	// MaxPageSize Maximum number of resources to return in a single page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token indicating the starting point for the page
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateContainerParams defines parameters for CreateContainer.
type CreateContainerParams struct {
	// Id Optional client-specified ID for the container. If not provided,
	// the server will generate an ID.
	//
	// Requirements (per AEP-122):
	// - 1-63 characters long
	// - Start with a lowercase letter or digit
	// - Contain only lowercase letters, numbers, and hyphens
	// - End with letter or number
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateContainerJSONRequestBody defines body for CreateContainer for application/json ContentType.
type CreateContainerJSONRequestBody = Container

// Getter for additional properties for ContainerCpu. Returns the specified
// element and whether it was found
func (a ContainerCpu) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerCpu
func (a *ContainerCpu) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerCpu to handle AdditionalProperties
func (a *ContainerCpu) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerCpu to handle AdditionalProperties
func (a ContainerCpu) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerEnvVar. Returns the specified
// element and whether it was found
func (a ContainerEnvVar) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerEnvVar
func (a *ContainerEnvVar) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerEnvVar to handle AdditionalProperties
func (a *ContainerEnvVar) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerEnvVar to handle AdditionalProperties
func (a ContainerEnvVar) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerImage. Returns the specified
// element and whether it was found
func (a ContainerImage) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerImage
func (a *ContainerImage) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerImage to handle AdditionalProperties
func (a *ContainerImage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["reference"]; found {
		err = json.Unmarshal(raw, &a.Reference)
		if err != nil {
			return fmt.Errorf("error reading 'reference': %w", err)
		}
		delete(object, "reference")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerImage to handle AdditionalProperties
func (a ContainerImage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["reference"], err = json.Marshal(a.Reference)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'reference': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerMemory. Returns the specified
// element and whether it was found
func (a ContainerMemory) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerMemory
func (a *ContainerMemory) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerMemory to handle AdditionalProperties
func (a *ContainerMemory) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerMemory to handle AdditionalProperties
func (a ContainerMemory) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerNetwork. Returns the specified
// element and whether it was found
func (a ContainerNetwork) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerNetwork
func (a *ContainerNetwork) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerNetwork to handle AdditionalProperties
func (a *ContainerNetwork) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ip"]; found {
		err = json.Unmarshal(raw, &a.Ip)
		if err != nil {
			return fmt.Errorf("error reading 'ip': %w", err)
		}
		delete(object, "ip")
	}

	if raw, found := object["ports"]; found {
		err = json.Unmarshal(raw, &a.Ports)
		if err != nil {
			return fmt.Errorf("error reading 'ports': %w", err)
		}
		delete(object, "ports")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerNetwork to handle AdditionalProperties
func (a ContainerNetwork) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Ip != nil {
		object["ip"], err = json.Marshal(a.Ip)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip': %w", err)
		}
	}

	if a.Ports != nil {
		object["ports"], err = json.Marshal(a.Ports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ports': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerPort. Returns the specified
// element and whether it was found
func (a ContainerPort) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerPort
func (a *ContainerPort) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a *ContainerPort) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["container_port"]; found {
		err = json.Unmarshal(raw, &a.ContainerPort)
		if err != nil {
			return fmt.Errorf("error reading 'container_port': %w", err)
		}
		delete(object, "container_port")
	}

	if raw, found := object["visibility"]; found {
		err = json.Unmarshal(raw, &a.Visibility)
		if err != nil {
			return fmt.Errorf("error reading 'visibility': %w", err)
		}
		delete(object, "visibility")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a ContainerPort) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["container_port"], err = json.Marshal(a.ContainerPort)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'container_port': %w", err)
	}

	object["visibility"], err = json.Marshal(a.Visibility)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'visibility': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerProcess. Returns the specified
// element and whether it was found
func (a ContainerProcess) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerProcess
func (a *ContainerProcess) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerProcess to handle AdditionalProperties
func (a *ContainerProcess) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["args"]; found {
		err = json.Unmarshal(raw, &a.Args)
		if err != nil {
			return fmt.Errorf("error reading 'args': %w", err)
		}
		delete(object, "args")
	}

	if raw, found := object["command"]; found {
		err = json.Unmarshal(raw, &a.Command)
		if err != nil {
			return fmt.Errorf("error reading 'command': %w", err)
		}
		delete(object, "command")
	}

	if raw, found := object["env"]; found {
		err = json.Unmarshal(raw, &a.Env)
		if err != nil {
			return fmt.Errorf("error reading 'env': %w", err)
		}
		delete(object, "env")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerProcess to handle AdditionalProperties
func (a ContainerProcess) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Args != nil {
		object["args"], err = json.Marshal(a.Args)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'args': %w", err)
		}
	}

	if a.Command != nil {
		object["command"], err = json.Marshal(a.Command)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'command': %w", err)
		}
	}

	if a.Env != nil {
		object["env"], err = json.Marshal(a.Env)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'env': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerResources. Returns the specified
// element and whether it was found
func (a ContainerResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerResources
func (a *ContainerResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerResources to handle AdditionalProperties
func (a *ContainerResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerResources to handle AdditionalProperties
func (a ContainerResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cpu"], err = json.Marshal(a.Cpu)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
	}

	object["memory"], err = json.Marshal(a.Memory)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
