// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb61Mjt7L/V7om+QB7/ARDznLr1CmvcRZXwLiwyb2nFi4lz7RtJTPSRNIYnMD/fkuP",
	"eXnG4M1jbz5svsRo1K1Wq/vXD2l/83wexZwhU9I7+82LiSARKhTmr0GYSIViFEyIWumBAKUvaKwoZ96Z",
	"dz64aoa4xhB8OxEESp4IH4EGyBRdUBRwQANYUAyDQ6/hUU0Xa24Nj5EIvTPPTxfxGp7AXxIqMPDOlEiw",
	"4Ul/hRGxgimFQlP/7yfS/LXTfH9/4H4073/rNE67L+n44b+/9Rqe2sSau1SCsqX38vKScjM76w+uJoKv",
	"aYDigrq9lzfXH1w1ZYw+XVAfYjcXVmZyw4sFj1EoioaSLJGph5DMMbR/BwHVbEg4Kc3bkqmxteSlYQCK",
	"Q0SUvwLDVsLBgguYE4ERKhIe5nvj85/QV5rPnEh8CHhEtH63d/KBSAT7ETQrtcLswA6wtWw14M7DJxLF",
	"IbZ8Ht15h1X96aNbCPKAbF1dYUwiBL4wnEd62pCt9TYSibulzznHIVELLiLLeEGSUHln3s/JHNdUKG9b",
	"TTMilqggpdrek9fwkCWRd/apyCKTwLuvkUBgiFqFNCJLrO7vOranCXyNQtAAszUdIVjCqtXVnJVzqhqL",
	"q7pRRBhZYgDzDfQHV+2LTYxiuqILVTXBmD4gC2JOmaqy/iGZo2CoUEJ/MoJ0ItzeXMIBWRMaknmI8LhC",
	"BjfD/vl/Do0zkuCahZvUGSta8zmTPMSHRNA6nSEzooKbBrc3oz+ymECi8EHRqOaAZjRCqUgUW65FC38k",
	"EiytBhhtMERbV0AUNg2zPdamwWvgVwN6LZiiWKNoLpGh0GvD7e3oHOgCGFfghxSZSuEFA1hTYoT+Nw3+",
	"Bb8kKDaQITFwZjdAOWvBrcQAKDMnp3FUAmGBodV/WaBtaRew/uyded2jY+ydnH7XxH++nze7R8Fxk/RO",
	"Tpu9o9PTbq/7Xa/T6WhzqgPYpvv1roytbypMO57P2YIu6+HotNdE5vMAA8inGqdKj434PkrZggmPk9Ao",
	"0Jxs+lkqohIJVFoLasEwitUGgkRLAJPh+Hw0/tiAyc31j6Pp6Hps/uICvu+PLofnhhxla5+txLWh7yY9",
	"c6t1gwZUFiEo078bk+09D+JNibTZaIm+Fbjwzrxv2nkIb7sQ13YgM9VTNYlRV3Ubg0QIZCpVp4PwKpA6",
	"hXoNr6hRr+EZ7XsNz+rVa3jnw8vhzH4zP83g7bj/Y3902f9wOdTw+/oOG95TU6/bXBOhUwSpBUj3Y+TM",
	"pSkPl0UrfUvlLA1mQpdGCzuojlenl/aWqfohQilrY8lFEhHW1CowKOjmAZnzRFntl85kH4NI4uB3Q2NI",
	"pALL4Pfi40sxb/tkzfN+O/DpUyUYN1OwLOR05oAzL/nN/XrRPOIwESQsOJHX8CRlyyQkIh/N4y7xo6Yb",
	"bEoUa+pjM83dWoEftShvp0QveSy+pLImaE7IkjIDPSGVSjtHQYpy9M0+VJhcVkmpwkju6cBenkEQIchG",
	"/83wST3EZIkPiv+MNQnfTA/r/GuBOo3UR65pQNNoWQTKJDRp7P7pyhUqEhBFqqulX2rysLKS/nB+/ANu",
	"mmsSJgiWVc2KFfFtkfGGE6YOoSe7EEuk4fzDPyVccKkwcHqAyG23ZSdfJVLBHCFh9JcE4ZGqFbVepmya",
	"aiAsJj62dgXZz6liyq5mNne/+9DGPMAam9TDYGNuIkxe8ebZ+ZwpwcOHOCQM37RdO3mi56YR6JGLn52D",
	"vEb632aaJXrFGqcuBJb3NXUer6ny2o2yOFGQ/plvl+zcbFSw9T18NHMNbW6pxvegs6fzYlY3CPWwSkvR",
	"16jLdauOOHbbD1ZZO5QC+mspQ00t9y5FrzsvT2Smk1Yh/KeKqiud1iikWemVmiOijAtwM3fXoN3WcefO",
	"O2zBFYljk+ZqZyFhuNFgRhjkNUXKK02ctZ6IonMaUrXR5bOgT3BwPZhAr/UE/zJ+3G0dPP2je3x4aFJm",
	"HYjCNQaGNaSdDl3GTVHpnFuz7Q+u4CKZt970xNIZ5Epp5LZU66bbjlJN0OwMMH4H2rrKllzjqEldAThO",
	"orkuJRbgVzjK/KS7jePGSS6pPoClDUJ+nLzGdTC5BZ8LlBCjqFlDa4IyGulVjur4RxhxsamLLnp8B9eC",
	"6Zx+/HDn6V/HR/rXYbkEOv34YQt9u833959MaXNw9eH544fn2YfDb+uaE1JxUZvITe2Ht0U76qSynXQ6",
	"NcLp779PujqEHArBa5oLN98P4H3v5DvjKSElTAHqmdoPYs4kwsFE8HmIEZyjItRF14vZbAL9yUgetu7Y",
	"HTvHBWUYQOym6tXlmf4C8AwzDTG6yn+GGVUhwrOlt4kyPJtZzey/563/u78sr1ar1XaryDZlaxLSoEnE",
	"Mol0bvwMIzsEhaFepwN11Iyr5oInLIBnGHMF6e9ep1c7n4Q6Mdg08YlKJeEZ+nYAsoFe530tZcJiwXXd",
	"qrOKpoZatYFnuC0OQzbcOzqC+t1a2DO7dD9tOwHM4cIznOzYasLy/sozpNBfHj3pHNfSxigiKjVsNQNk",
	"FLWKJtkYZGO9HfQJI4la6d35JmnW+94e6XW6mvaOjbnCM6guqZF5mxERCIEzPJdbabi6Y/NEmXbKBhVg",
	"RJWynTLCNrAiLAh1lDOGqG05DPmjoV3p3I/+ikFThsnyjvmcrfViLjItuHgkImiWI4rO60wQ0YBMKEOh",
	"Q+RdFX8D4zxvZpz4pKHCJiNZpqK4Db7ctzWgj/V9WKkI82sQSbuewAUa0jyWZ/ytw5e4Z/VeImgzo63H",
	"wfoWgvFw1z/wLdJnTClTx0ca+smThf6T9+8LgaDb6dSFAqWPrAZvV1yohj2+XJEyiSIiNmnrwllj3Qbq",
	"06Oyzlx+tKFsae3MaMwF9TQbWikVy7N2O/AjXVxq4G0tqVolc11e7gQtr7EvZQZY+5OUMWt/uooH7k+6",
	"5ab7E6b49llLpQD2OURVMNZZ2J4mX9uGMvirw9xo/GP/cnTev/l4ezUcz7xG/ml8Pfv++nZ8XhzrX5oG",
	"1PB/RtPZtPhhMry5Gk2no+vx+XA8GpaIbsf929nFcDwbDfqz8qfReDa8Gfcvt6ZnjajS8OTmejCcTvUH",
	"zWz2H+9+O311Fm49ry5TvUAS1vVB7Xjq/5KyZYiKs6wnXsHH+nbqgDDOqE9C2091zlxgkqdLKyvJPn3S",
	"XYhVlLmG92Yf5vVokrWFt6qt0ir7NKmyXe601j26gvUNwSn6nAXmsHyEqQFvYR04k/H4VEPzjiUKUL2z",
	"+JtOYJ7QMMgKtcyrColvq9PqfHZ70ZlqdnruMjmvuNy+P7sD6VRe7DraobTpaCw7u5nOu5DZWX1GE9LR",
	"6M1V7qHru2N22a0OpSPNmx3lrs6O22o/eqvHULkery01Cs2aigHYb39KxfqYs5LFOrL7h+vUAuc3Ge9R",
	"oBbY/W0q03qZvmRJ+mLfDvC0jUh8c9ru9cf54AomNohr3xXG7VyAd0Hd51Ex1lf7wmmdk73S6E9GJv01",
	"1+c6lytcRrs+vOkc3WAAF0RBP1jrjDpI20BwZe7dTV150B9c2Y5RfvtuauGZzq31SlRCTIRKo9Y51bqY",
	"J8rw40lQ4nauubmdGK5O6OzuEEK6QH/jh+ntv6a7Yz6JialFKEqgzA+TQG8svRhuQIAh2l+aqwvIEWdU",
	"cX0yRuRvvgGt7xtcahktRqTdyzvWhHfvxiTCs3fvoIRhsf3m1KyTCj0l7Rrab0kccx1FJu5VhtRT0vcX",
	"jfwByNb0Hy1sm9nnG0Yi6sPBnEgMgLPtrpyEvI7lLG3OHVqW1zHaHRleg5thfzZsgL20a5hbYlOthdRH",
	"JrFggf2Y+CuEIxOLygb4+PjYIuZzi4tl29HK9uVoMBxPh01NkxcsnhYotaDUJicFmyyEqTT6vTQ8HiMj",
	"MfXOvONWp9VzIc1AY5vEtL3ukjBekW67eMm0RFWXfahEMAkE4srVFQnD3PYLz0pshbjlQC3PiGX1OQrc",
	"NdagcPtVeCb2qf76ydTSqPxVWkvtuIIyL8LMk4f8SVjhcqv4BqwCNRUstnUmsAzv3Tq6tBZGOwYUY/tY",
	"p27piDzZuzVJf8XS6tnLpJPOayWuKWpfCyUv5gbcNt3MWR51Oik2oo2EJI5DFy7bP0mbX+WC7HG1YC40",
	"DfK+cRv50vB6ry7vyql/fJ4YtglZI0DattMZHUpl1+9+ufW3WlJ2/eMvt36loaYlOPmyJ+BaitK2FNFN",
	"bHiulZKaSRExdJwny+JLDGkeO8S87uJ8YJ5baRxi+FiNvSb0lp+ztWBWuBBKg5qOrERumL8SnPFE/tcd",
	"M3CVPV8TDvBoFGFAicLQdepI+gTIBUJzqQsfhzNoVx4ajIKXO6Y4xDwMS0+QdF1CGUpp+3xlQLR7HOQ3",
	"iK8h4sC+9yJS0iXDoP6ZbH84aXaPjw9bMFoAt+3MhkFOd1LpWzKt2Nvb0Xnl8plEnC3NuaULVKHeXuzV",
	"IR8NvD/1we29rdtQqg882PzZCGdNu/xe+KUCrN2/Ztnt0902W0YVzeHlK7z+/8Jrr/P+y0mQGgMp3RkZ",
	"MY6OvuRByDTFzh9K53fwf8uoYyHVRY3Ck55q4Hlp7EiN077KWxmyuQcqtS5d8fZ2JvwR1UXegvyL0riL",
	"tD1UUeTFPlJvKdbR+Cv0fy4o1C3ymjoLMdIqM0RV03AYOcCTWRVqSo70EG10zz5tR3WoDep3rBDVy/nB",
	"Iw1DHfYERnyNASwEj6weNlJhBJz5heXMhTcqrA3j52ZHO8N43RnlU9rlfx9Tk9j3apIjt4lcHeVo8RWt",
	"e18erVn6LOBvCYzWSEsP1mqz8TchL3AvO4xz5j1jp4S8q0SV3HqGXIuDf5nbdL5k2uaU8tX7vnpfrfd9",
	"xLxyTW2lPitxbzHra8AbzvMOd9tYveOxK0Lk7V/IXE/m9dog7+HsuOE0Ab+WNs0v7l/+LwAA//+4XcIa",
	"AToAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
