// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ACMProviderHintsPlatform.
const (
	Baremetal ACMProviderHintsPlatform = "baremetal"
	Kubevirt  ACMProviderHintsPlatform = "kubevirt"
)

// Valid indicates whether the value is a known member of the ACMProviderHintsPlatform enum.
func (e ACMProviderHintsPlatform) Valid() bool {
	switch e {
	case Baremetal:
		return true
	case Kubevirt:
		return true
	default:
		return false
	}
}

// Defines values for ClusterStatus.
const (
	ClusterStatusDELETED      ClusterStatus = "DELETED"
	ClusterStatusDELETING     ClusterStatus = "DELETING"
	ClusterStatusFAILED       ClusterStatus = "FAILED"
	ClusterStatusPENDING      ClusterStatus = "PENDING"
	ClusterStatusPROVISIONING ClusterStatus = "PROVISIONING"
	ClusterStatusREADY        ClusterStatus = "READY"
	ClusterStatusUNAVAILABLE  ClusterStatus = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ClusterStatus enum.
func (e ClusterStatus) Valid() bool {
	switch e {
	case ClusterStatusDELETED:
		return true
	case ClusterStatusDELETING:
		return true
	case ClusterStatusFAILED:
		return true
	case ClusterStatusPENDING:
		return true
	case ClusterStatusPROVISIONING:
		return true
	case ClusterStatusREADY:
		return true
	case ClusterStatusUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for ClusterSpecServiceType.
const (
	ClusterSpecServiceTypeCluster ClusterSpecServiceType = "cluster"
)

// Valid indicates whether the value is a known member of the ClusterSpecServiceType enum.
func (e ClusterSpecServiceType) Valid() bool {
	switch e {
	case ClusterSpecServiceTypeCluster:
		return true
	default:
		return false
	}
}

// Defines values for ControlPlaneSpecCount.
const (
	N1 ControlPlaneSpecCount = 1
	N3 ControlPlaneSpecCount = 3
	N5 ControlPlaneSpecCount = 5
)

// Valid indicates whether the value is a known member of the ControlPlaneSpecCount enum.
func (e ControlPlaneSpecCount) Valid() bool {
	switch e {
	case N1:
		return true
	case N3:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ErrorTypeALREADYEXISTS       ErrorType = "https://dcm-project.github.io/problems/already-exists"
	ErrorTypeINTERNAL            ErrorType = "https://dcm-project.github.io/problems/internal"
	ErrorTypeINVALIDARGUMENT     ErrorType = "https://dcm-project.github.io/problems/invalid-argument"
	ErrorTypeNOTFOUND            ErrorType = "https://dcm-project.github.io/problems/not-found"
	ErrorTypePERMISSIONDENIED    ErrorType = "https://dcm-project.github.io/problems/permission-denied"
	ErrorTypeUNAUTHENTICATED     ErrorType = "https://dcm-project.github.io/problems/unauthenticated"
	ErrorTypeUNAVAILABLE         ErrorType = "https://dcm-project.github.io/problems/unavailable"
	ErrorTypeUNPROCESSABLEENTITY ErrorType = "https://dcm-project.github.io/problems/unprocessable-entity"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ErrorTypeALREADYEXISTS:
		return true
	case ErrorTypeINTERNAL:
		return true
	case ErrorTypeINVALIDARGUMENT:
		return true
	case ErrorTypeNOTFOUND:
		return true
	case ErrorTypePERMISSIONDENIED:
		return true
	case ErrorTypeUNAUTHENTICATED:
		return true
	case ErrorTypeUNAVAILABLE:
		return true
	case ErrorTypeUNPROCESSABLEENTITY:
		return true
	default:
		return false
	}
}

// ACMProviderHints ACM-specific provider hints
type ACMProviderHints struct {
	// AgentLabels Labels to match agents (for baremetal)
	AgentLabels *map[string]string `json:"agent_labels,omitempty"`

	// BaseDomain Base domain for the cluster (e.g., "example.com")
	BaseDomain *string `json:"base_domain,omitempty"`

	// InfraEnv Name of the InfraEnv to use (for baremetal)
	InfraEnv *string `json:"infra_env,omitempty"`

	// Platform Target platform for the cluster
	Platform *ACMProviderHintsPlatform `json:"platform,omitempty"`

	// ReleaseImage Optional override for the release image
	ReleaseImage *string `json:"release_image,omitempty"`
}

// ACMProviderHintsPlatform Target platform for the cluster
type ACMProviderHintsPlatform string

// Cluster A cluster resource managed by ACM/HyperShift
type Cluster struct {
	// ApiEndpoint Kubernetes API endpoint URL (available when READY)
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// ConsoleUri OpenShift console URI (available when READY)
	ConsoleUri *string `json:"console_uri,omitempty"`

	// CreateTime Timestamp when the cluster was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM-level resource identifier. Server-generated UUID if not client-specified via the ?id= query parameter on creation. Used in URL paths and the path field.
	Id *string `json:"id,omitempty"`

	// Kubeconfig Base64-encoded kubeconfig for cluster access. Populated when cluster status is READY. Empty during PENDING, PROVISIONING, or FAILED states.
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// Path Resource path for this cluster
	Path *string `json:"path,omitempty"`

	// Spec Service-type-specific input specification for a cluster
	Spec ClusterSpec `json:"spec"`

	// Status Current status of the cluster
	Status *ClusterStatus `json:"status,omitempty"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the cluster was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ClusterStatus Current status of the cluster
type ClusterStatus string

// ClusterList Paginated list of clusters
type ClusterList struct {
	// Clusters List of clusters
	Clusters *[]Cluster `json:"clusters,omitempty"`

	// NextPageToken Token to fetch the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ClusterMetadata Metadata for the cluster
type ClusterMetadata struct {
	// Labels Key-value labels for the cluster
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable cluster name. Used as the K8s HostedCluster metadata.name. Must be unique within the target namespace.
	Name string `json:"name"`
}

// ClusterNodes Node configuration for the cluster
type ClusterNodes struct {
	// ControlPlane Control plane node specification
	ControlPlane *ControlPlaneSpec `json:"control_plane,omitempty"`

	// Workers Worker node specification
	Workers *WorkerSpec `json:"workers,omitempty"`
}

// ClusterSpec Service-type-specific input specification for a cluster
type ClusterSpec struct {
	// Metadata Metadata for the cluster
	Metadata ClusterMetadata `json:"metadata"`

	// Nodes Node configuration for the cluster
	Nodes *ClusterNodes `json:"nodes,omitempty"`

	// ProviderHints Provider-specific configuration hints
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier. Must be "cluster" for this SP.
	ServiceType ClusterSpecServiceType `json:"service_type"`

	// Version Kubernetes minor version for the cluster (e.g., "1.30"). Mapped internally to an OpenShift version via the compatibility matrix (OCP 4.x = K8s 1.(x+13)) and resolved to a ClusterImageSet on the ACM Hub.
	Version string `json:"version"`
}

// ClusterSpecServiceType Service type identifier. Must be "cluster" for this SP.
type ClusterSpecServiceType string

// ControlPlaneSpec Control plane node specification
type ControlPlaneSpec struct {
	// Count Number of control plane nodes
	Count *ControlPlaneSpecCount `json:"count,omitempty"`

	// Cpu Number of CPU cores per control plane node
	Cpu *int `json:"cpu,omitempty"`

	// Memory Memory per control plane node (e.g., "16GB", "32GB")
	Memory *string `json:"memory,omitempty"`

	// Storage Storage per control plane node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// ControlPlaneSpecCount Number of control plane nodes
type ControlPlaneSpecCount int

// Error RFC 9457 compliant error response (Problem Details for HTTP APIs).
//
// Defined problem types:
//
//	| Type URI | Title | HTTP Status |
//	|----------|-------|-------------|
//	| .../problems/invalid-argument | Invalid argument | 400 |
//	| .../problems/not-found | Not found | 404 |
//	| .../problems/already-exists | Already exists | 409 |
//	| .../problems/unprocessable-entity | Unprocessable entity | 422 |
//	| .../problems/internal | Internal Server Error | 500 |
//	| .../problems/unavailable | Service unavailable | 503 |
//	| .../problems/permission-denied | Permission denied | 403 |
//	| .../problems/unauthenticated | Unauthenticated | 401 |
//
// Note: permission-denied and unauthenticated are defined in the enum
// but not yet emitted by any handler. Titles follow the humanized-slug
// convention for forward-compatibility with K8s Container SP.
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short, human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the error type
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`

	// Type Resource type identifier
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since SP started
	Uptime *int `json:"uptime,omitempty"`

	// Version SP build version string
	Version *string `json:"version,omitempty"`
}

// ProviderHints Provider-specific configuration hints
type ProviderHints struct {
	// Acm ACM-specific provider hints
	Acm                  *ACMProviderHints      `json:"acm,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WorkerSpec Worker node specification
type WorkerSpec struct {
	// Count Number of worker nodes
	Count *int `json:"count,omitempty"`

	// Cpu Number of CPU cores per worker node
	Cpu *int `json:"cpu,omitempty"`

	// Memory Memory per worker node (e.g., "16GB", "32GB")
	Memory *string `json:"memory,omitempty"`

	// Storage Storage per worker node (e.g., "120GB", "500GB")
	Storage *string `json:"storage,omitempty"`
}

// ClusterIdPath defines model for ClusterIdPath.
type ClusterIdPath = string

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Client-assigned resource identifier (AEP-133). If omitted, the server generates a UUID. Must be unique among all resources managed by this SP.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = Cluster

// Getter for additional properties for ProviderHints. Returns the specified
// element and whether it was found
func (a ProviderHints) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProviderHints
func (a *ProviderHints) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a *ProviderHints) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["acm"]; found {
		err = json.Unmarshal(raw, &a.Acm)
		if err != nil {
			return fmt.Errorf("error reading 'acm': %w", err)
		}
		delete(object, "acm")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a ProviderHints) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Acm != nil {
		object["acm"], err = json.Marshal(a.Acm)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'acm': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
